name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Disable CI checks
      run: echo "CI=false" >> $GITHUB_ENV

    - name: Force Build React App (Ignore warnings)
      run: npm run build
    
    - name: Deploy React app to GitHub Pages
      uses: omkartapale/react-deployment-gh-pages@v1.0.0
